# Generated by Django 5.2.12 on 2026-05-09 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0002_course_url_movie_image_url_paymenttransaction_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('movies', 'Movies'), ('box_office', 'Box Office'), ('awards', 'Awards'), ('streaming', 'Streaming'), ('tv', 'TV')], default='movies', max_length=40)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='Cinema.user')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', '-id'],
            },
        ),
    ]
