# Generated by Django 5.2.12 on 2026-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0003_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
