# Generated by Django 5.2.12 on 2026-05-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_alter_movie_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('primary_role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('screenwriter', 'Screenwriter'), ('dop', 'DOP'), ('producer', 'Producer')], default='actor', max_length=40)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='box_office_gross_egp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_in_cinemas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_now_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=80),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='showtime',
            name='cinema_name',
            field=models.CharField(blank=True, default='CEEMA Cinema', max_length=160),
        ),
        migrations.AddField(
            model_name='showtime',
            name='city',
            field=models.CharField(blank=True, default='Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.CreateModel(
            name='MovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('screenwriter', 'Screenwriter'), ('dop', 'DOP'), ('producer', 'Producer'), ('composer', 'Composer')], max_length=40)),
                ('character_name', models.CharField(blank=True, max_length=160)),
                ('billing_order', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='Cinema.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_credits', to='Cinema.person')),
            ],
            options={
                'ordering': ['billing_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('movie', 'person', 'job', 'character_name'), name='unique_movie_credit')],
            },
        ),
    ]
