# Generated by Django 5.2.12 on 2026-06-04 21:52

from django.db import migrations, models


def prepare_live_demo_data(apps, schema_editor):
    Course = apps.get_model("Cinema", "Course")
    Seat = apps.get_model("Cinema", "Seat")
    Showtime = apps.get_model("Cinema", "Showtime")

    course_urls = {
        "History of Cinema": "https://www.coursera.org/learn/film-images",
        "Film Criticism 101": "https://www.coursera.org/learn/composition-moving-image",
        "Cinematography Basics": "https://www.coursera.org/learn/camera-basics-for-video-foundations-for-video-creation",
    }
    for title, url in course_urls.items():
        Course.objects.filter(title=title).update(url=url)

    for showtime in Showtime.objects.all().iterator():
        existing = set(
            Seat.objects.filter(showtime=showtime).values_list("seat_number", flat=True)
        )
        seats = []
        for row in range(1, 9):
            row_letter = chr(64 + row)
            for column in range(1, 11):
                seat_number = f"{row_letter}{column}"
                if seat_number not in existing:
                    seats.append(
                        Seat(
                            showtime=showtime,
                            seat_number=seat_number,
                            status="available",
                            row=row,
                            column=column,
                        )
                    )
        Seat.objects.bulk_create(seats, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0005_person_movie_backdrop_url_movie_box_office_gross_egp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(prepare_live_demo_data, migrations.RunPython.noop),
    ]
